version: 0.2

phases:
  install:
    commands:
      - npm install
  pre-build:
    commands:
      - sed -i 's/_DB_CONNECTION_STRING_/$DBConnectionString/g' app.js
      - sed -i 's/_AWS_ACCESS_KEY_/$PixelisticAccesKey/g' aws-config.json
      - sed -i 's/_AWS_SECRET_KEY_/$PixelisticSecretKey/g' aws-config.json
artifacts:
  files:
    - '**/*'